local BKA = BFAKeyAlerts

local clientLocale = GetLocale and GetLocale() or "enUS"
BKA.locale = clientLocale == "ruRU" and "ruRU" or "enUS"

local EN = {
    ADDON_TITLE = "BFA Key Alerts",
    DISCORD_TITLE = "Discord",
    PREVIEW_PLAYER = "Player",
    PREVIEW_TANK = "Tank",
    PREVIEW_FIXED_FRONTAL = "Fixed frontal",
    PREVIEW_TEAM_FRONTAL = "Frontal on teammate",
    PREVIEW_LOCKED_FRONTAL = "Personal locked frontal",
    PREVIEW_TRACKING_FRONTAL = "Personal tracking frontal",
    PREVIEW_FRONTAL_SOON = "Frontal prediction",
    PREVIEW_INTERRUPT = "Active interrupt",
    PREVIEW_GROUP_DAMAGE = "Group damage",
    DRAG = "drag",
    READY = "READY",
    DOWN = "DOWN",
    COOLDOWN_FMT = "CD: %ss",
    UNAVAILABLE = "Unavailable",
    UNKNOWN_READY = "Readiness not confirmed yet",
    GROUP_CONTROL = "Group control",
    GROUP_CONTROL_HEADER = "GROUP CONTROL",
    KICK_SUMMARY_FMT = "K %d/%d  |  CC %d",
    KEYSTONE_TIMER = "Keystone timer",
    DUNGEON = "Dungeon",
    KEY_PREVIEW_BOSS = "Unlocked - drag the blue handle above",
    MYTHIC_SETUP = "MYTHIC+  /  POSITION SETUP",
    MYTHIC_KEY_FMT = "MYTHIC+  /  KEY +%d",
    AFFIX_WAIT = "Affixes appear after the key starts",
    FORCES_FMT = "Forces %.1f%%  |  remaining %.1f%%",
    FORCES_EMPTY = "ENEMY FORCES   -",
    BOSSES_FMT = "BOSSES   %d / %d   |   REMAINING %d",
    BOSSES_DONE = "All bosses defeated",
    WAIT_OBJECTIVES = "Waiting for dungeon objectives...",
    FOOTER_FMT = "Elapsed %s   |   Deaths %d   |   Penalty %s",
    YOU = "YOU",
    TANK = "TANK",
    FIXED = "FIXED",
    LOCKED = "LOCKED",
    TRACK = "TRACK",
    TRACKING = "TRACKING",
    SOON = "SOON",
    YOU_ACTION_FMT = "YOU - %s",
    SOON_ACTION_FMT = "SOON - %s",
    ACTION_SOON_FMT = "%s SOON",
    SPELL_FALLBACK = "Spell %s",
    UPDATE_AVAILABLE_FMT = "New version %s is available. GitHub: %s",
    ON = "ON",
    OFF = "OFF",
    ADDON = "addon",
    CENTER_ALERTS = "center alerts",
    NAMEPLATES = "nameplates",
    GROUP_KICKS = "group kicks",
    SOUND = "sound",
    FRONTAL_DETAILS = "frontal target details",
    CLICKABLE_NAMEPLATES = "clickable nameplate alerts",
    SOUND_RESET_DONE = "Combat sound actions reset to ON",
    SLASH_HELP = "/bka config, alerts on|off, plates on|off, kicks on|off, keytimer on|off, frontal on|off, plateclick on|off|status, soundpreview <name|all|keyupgrade>, soundreset, unlock, lock, on|off, sound on|off",
    PLATE_API_UNAVAILABLE = "plateclick: BFA nameplate click API unavailable",
    PLATE_STATUS_FMT = "plateclick: enabled=%s, applied=%s, clickThrough=%s, insets=%s",
    SOUND_PREVIEW_LIST_FMT = "soundpreview: %s",
    REMAINING = "remaining",
    REMAINING_COUNT_FMT = "%d remaining",
    OVER = "OVER",
    SPAWNED = "SPAWNED",
    NEXT_ADDS = "Next adds",
    COUNCIL_STAGE = "Council stage",
    REBAN = "Reban",
    TZALA = "T'zala",
    STAGE_TWO = "Stage 2",
    VIQ_GOTH_STAGE = "Viq'Goth stage",
    DEMOLISHING_TERROR = "Demolishing Terror",
    HEART_GUARDIAN = "Heart Guardian",
    PLAGUE_DOCTOR = "Plague Doctor",
    HOODOO_HEXER = "Hoodoo Hexer",
    INTERMISSION = "Intermission",
    INTERMISSION_OVER = "Intermission over",
    ENEMY_FORCES_TOOLTIP_FMT = "Enemy Forces: %.2f%%",
    MINIMAP_LEFT = "Left Click — Settings",
    MINIMAP_RIGHT = "Right Click — Discord",
    DISCORD_CONTACT = "Contact the developer",
    DISCORD_COPY_HINT = "Copy this link and open it in your browser:",
    CLOSE = "Close",
    OPT_SUBTITLE = "Mythic+ controls",
    OPT_GENERAL = "General",
    OPT_MECHANICS = "Mechanics",
    OPT_NAMEPLATES = "Nameplates",
    OPT_KICKS = "Group Kicks",
    OPT_KEYSTONE = "Keystone",
    OPT_SOUNDS = "Sounds",
    OPT_ENABLED = "Enable BFA Key Alerts",
    OPT_ENABLED_DESC = "Master switch for combat alerts and HUDs.",
    OPT_ALERTS = "Center alerts",
    OPT_ALERTS_DESC = "Show important mechanics in the center alert area.",
    OPT_MINIMAP_VISIBLE = "Show minimap icon",
    OPT_MINIMAP_DESC = "The settings window remains available with /bka config.",
    OPT_ALERT_LAYOUT = "Alert presentation",
    OPT_BAR = "Bar",
    OPT_ICON = "Icon",
    OPT_SCALE = "Scale",
    OPT_WIDTH = "Width",
    OPT_LOCK_TOGGLE = "Lock / unlock",
    OPT_RESET_POSITION = "Reset position",
    OPT_ROLE_FILTERS = "Role alerts",
    OPT_TANK = "Tank alerts",
    OPT_TANK_DESC = "Include mechanics marked for tanks.",
    OPT_HEALER = "Healer alerts",
    OPT_HEALER_DESC = "Include mechanics marked for healers.",
    OPT_DUNGEON_INFO = "Dungeon effects",
    OPT_INFESTED = "Infested / G’huun markers",
    OPT_INFESTED_DESC = "Show the BFA Season 1 Infested mechanic.",
    OPT_FORCES_TOOLTIP = "Enemy Forces in unit tooltip",
    OPT_FORCES_TOOLTIP_DESC = "Show confirmed mob contribution inside a supported Mythic dungeon.",
    OPT_NAMEPLATES_DESC = "Show BKA mechanic markers above enemy nameplates.",
    OPT_FRONTAL = "Frontal target details",
    OPT_FRONTAL_DESC = "Show the target and tracking state when confirmed.",
    OPT_CLICKABLE = "Clickable nameplate markers",
    OPT_EXPERIMENTAL = "Experimental",
    OPT_CLICK_WARNING = "Makes BKA markers part of the enemy nameplate click area so mobs can be targeted through them. May conflict with Plater, Threat Plates, or other nameplate addons.",
    OPT_ENEMY = "Enemy",
    OPT_CLICK_TARGET = "Click to target",
    OPT_KICKS_DESC = "Show party interrupt and control readiness.",
    OPT_ONLY_IN_KEY = "Only during an active key",
    OPT_ONLY_IN_KEY_DESC = "Hide the group tracker outside a running Mythic+ key.",
    OPT_ALPHA = "Background opacity",
    OPT_PLAYER = "Player",
    OPT_KEY_HUD = "Custom keystone HUD",
    OPT_KEY_HUD_DESC = "Show +3/+2/+1, forces, bosses, deaths, and penalty.",
    OPT_HIDE_BLIZZARD = "Hide Blizzard tracker",
    OPT_HIDE_BLIZZARD_DESC = "Hide the standard timer and objectives during an active key.",
    OPT_AUTO_INSERT = "Auto insert keystone",
    OPT_AUTO_INSERT_DESC = "Place your bag keystone in Font of Power when its window opens. Never starts the key.",
    OPT_SOUND = "Combat sounds",
    OPT_SOUND_DESC = "Enable spoken combat actions.",
    OPT_PER_ACTION = "Per-action sounds",
    OPT_SOUND_HINT = "Toggle each action or play it with the button beside it.",
    OPT_PLAY_ALL = "Play all",
    OPT_RESET_SOUNDS = "Reset sounds",
    OPT_PLAY_VICTORY = "Victory sound",
    NECROTIC_HEAL_FMT = "Healing and absorbs -%d%%",
    NECROTIC_TICK_FMT = "last tick %d",
    MAX_HEALTH_REDUCTION_FMT = "Max health -%d%%",
    ARMOR_REDUCTION_FMT = "Armor -%d%%",
    DAMAGE_DONE_INCREASE_FMT = "Damage done +%d%%",
    OILED_BLADE_FMT = "Healing received -75%",
    WITHERING_CURSE_FMT = "Damage taken +%d%%, damage done -%d%%",
}

local RU = {
    ADDON_TITLE = "BFA Key Alerts",
    DISCORD_TITLE = "Discord",
    PREVIEW_PLAYER = "Игрок",
    PREVIEW_TANK = "Танк",
    PREVIEW_FIXED_FRONTAL = "Фиксированный фронтал",
    PREVIEW_TEAM_FRONTAL = "Фронтал в союзника",
    PREVIEW_LOCKED_FRONTAL = "Фронтал в тебя с фиксацией",
    PREVIEW_TRACKING_FRONTAL = "Фронтал следит за тобой",
    PREVIEW_FRONTAL_SOON = "Скоро фронтал",
    PREVIEW_INTERRUPT = "Активный кик",
    PREVIEW_GROUP_DAMAGE = "Урон по группе",
    DRAG = "перетащи",
    READY = "ГОТОВО",
    DOWN = "НЕДОСТУПНО",
    COOLDOWN_FMT = "КД: %sс",
    UNAVAILABLE = "Недоступно",
    UNKNOWN_READY = "Готовность пока не подтверждена",
    GROUP_CONTROL = "Контроль группы",
    GROUP_CONTROL_HEADER = "КОНТРОЛЬ ГРУППЫ",
    KICK_SUMMARY_FMT = "КИК %d/%d  |  КОНТРОЛЬ %d",
    KEYSTONE_TIMER = "Таймер ключа",
    DUNGEON = "Подземелье",
    KEY_PREVIEW_BOSS = "Разблокировано - перетащи полоску сверху",
    MYTHIC_SETUP = "MYTHIC+  /  НАСТРОЙКА ПОЗИЦИИ",
    MYTHIC_KEY_FMT = "MYTHIC+  /  КЛЮЧ +%d",
    AFFIX_WAIT = "Аффиксы появятся после запуска ключа",
    FORCES_FMT = "Силы %.1f%%  |  осталось %.1f%%",
    FORCES_EMPTY = "СИЛЫ ПРОТИВНИКА   -",
    BOSSES_FMT = "БОССЫ   %d / %d   |   ОСТАЛОСЬ %d",
    BOSSES_DONE = "Все боссы повержены",
    WAIT_OBJECTIVES = "Ожидание целей подземелья...",
    FOOTER_FMT = "Прошло %s   |   Смертей %d   |   Штраф %s",
    YOU = "ТЫ",
    TANK = "ТАНК",
    FIXED = "ФИКСИРОВАН",
    LOCKED = "ЗАФИКСИРОВАН",
    TRACK = "СЛЕДИТ",
    TRACKING = "СЛЕДИТ ЗА ЦЕЛЬЮ",
    SOON = "СКОРО",
    YOU_ACTION_FMT = "ТЫ - %s",
    SOON_ACTION_FMT = "СКОРО - %s",
    ACTION_SOON_FMT = "%s СКОРО",
    SPELL_FALLBACK = "Спелл %s",
    UPDATE_AVAILABLE_FMT = "Доступна новая версия %s. GitHub: %s",
    ON = "ВКЛ",
    OFF = "ВЫКЛ",
    ADDON = "аддон",
    CENTER_ALERTS = "центральные предупреждения",
    NAMEPLATES = "неймплейты",
    GROUP_KICKS = "кики группы",
    SOUND = "звук",
    FRONTAL_DETAILS = "цель и режим фронтала",
    CLICKABLE_NAMEPLATES = "кликабельные алерты на неймплейтах",
    SOUND_RESET_DONE = "Боевые звуки сброшены и включены",
    SLASH_HELP = "/bka config, alerts on|off, plates on|off, kicks on|off, keytimer on|off, frontal on|off, plateclick on|off|status, soundpreview <name|all|keyupgrade>, soundreset, unlock, lock, on|off, sound on|off",
    PLATE_API_UNAVAILABLE = "plateclick: API клика по неймплейтам BFA недоступен",
    PLATE_STATUS_FMT = "plateclick: включено=%s, применено=%s, сквозной клик=%s, границы=%s",
    SOUND_PREVIEW_LIST_FMT = "soundpreview: %s",
    REMAINING = "осталось",
    REMAINING_COUNT_FMT = "Осталось %d",
    OVER = "ЗАВЕРШЕНО",
    SPAWNED = "ПОЯВИЛСЯ",
    NEXT_ADDS = "Скоро подкрепление",
    COUNCIL_STAGE = "Этап совета",
    REBAN = "Ребан",
    TZALA = "Т'зала",
    STAGE_TWO = "Этап 2",
    VIQ_GOTH_STAGE = "Этап Вик'Гота",
    DEMOLISHING_TERROR = "Разрушительный ужас",
    HEART_GUARDIAN = "Страж сердца",
    PLAGUE_DOCTOR = "Чумной доктор",
    HOODOO_HEXER = "Колдун худу",
    INTERMISSION = "Переходка",
    INTERMISSION_OVER = "Переходка закончилась",
    ENEMY_FORCES_TOOLTIP_FMT = "Силы противника: %.2f%%",
    MINIMAP_LEFT = "ЛКМ — настройки",
    MINIMAP_RIGHT = "ПКМ — Discord",
    DISCORD_CONTACT = "Написать разработчику",
    DISCORD_COPY_HINT = "Скопируйте ссылку и откройте её в браузере:",
    CLOSE = "Закрыть",
    OPT_SUBTITLE = "Настройки Mythic+",
    OPT_GENERAL = "Основное",
    OPT_MECHANICS = "Механики",
    OPT_NAMEPLATES = "Неймплейты",
    OPT_KICKS = "Кики группы",
    OPT_KEYSTONE = "Ключ",
    OPT_SOUNDS = "Звуки",
    OPT_ENABLED = "Включить BFA Key Alerts",
    OPT_ENABLED_DESC = "Общий переключатель предупреждений и панелей.",
    OPT_ALERTS = "Центральные предупреждения",
    OPT_ALERTS_DESC = "Показывать важные механики в центре экрана.",
    OPT_MINIMAP_VISIBLE = "Показывать кнопку у миникарты",
    OPT_MINIMAP_DESC = "Настройки останутся доступны через /bka config.",
    OPT_ALERT_LAYOUT = "Вид предупреждений",
    OPT_BAR = "Полоса",
    OPT_ICON = "Иконка",
    OPT_SCALE = "Масштаб",
    OPT_WIDTH = "Ширина",
    OPT_LOCK_TOGGLE = "Закрепить / открепить",
    OPT_RESET_POSITION = "Сбросить положение",
    OPT_ROLE_FILTERS = "Ролевые предупреждения",
    OPT_TANK = "Танковые предупреждения",
    OPT_TANK_DESC = "Показывать механики для танков.",
    OPT_HEALER = "Предупреждения для хилеров",
    OPT_HEALER_DESC = "Показывать механики для хилеров.",
    OPT_DUNGEON_INFO = "Эффекты подземелья",
    OPT_INFESTED = "Метки Заражённых / Г’ууна",
    OPT_INFESTED_DESC = "Показывать механику Infested первого сезона BFA.",
    OPT_FORCES_TOOLTIP = "Силы противника в подсказке",
    OPT_FORCES_TOOLTIP_DESC = "Показывать подтверждённый вклад моба в подходящем мифическом подземелье.",
    OPT_NAMEPLATES_DESC = "Показывать маркеры механик BKA над неймплейтами врагов.",
    OPT_FRONTAL = "Детали фронтала",
    OPT_FRONTAL_DESC = "Показывать цель и режим слежения, когда они подтверждены.",
    OPT_CLICKABLE = "Кликабельные маркеры неймплейтов",
    OPT_EXPERIMENTAL = "Экспериментальная функция",
    OPT_CLICK_WARNING = "Позволяет кликать по BKA-маркерам над неймплейтами и брать моба в цель. Может конфликтовать с Plater, Threat Plates и другими аддонами, изменяющими неймплейты.",
    OPT_ENEMY = "Противник",
    OPT_CLICK_TARGET = "Клик для цели",
    OPT_KICKS_DESC = "Показывать готовность киков и контроля группы.",
    OPT_ONLY_IN_KEY = "Только в активном ключе",
    OPT_ONLY_IN_KEY_DESC = "Скрывать панель группы вне запущенного Mythic+ ключа.",
    OPT_ALPHA = "Прозрачность фона",
    OPT_PLAYER = "Игрок",
    OPT_KEY_HUD = "Свой таймер ключа",
    OPT_KEY_HUD_DESC = "Показывать +3/+2/+1, силы, боссов, смерти и штраф.",
    OPT_HIDE_BLIZZARD = "Скрыть стандартный таймер",
    OPT_HIDE_BLIZZARD_DESC = "Скрывать стандартный таймер и цели в активном ключе.",
    OPT_AUTO_INSERT = "Автоматически вставлять ключ",
    OPT_AUTO_INSERT_DESC = "Вставлять ключ из сумки при открытии окна Font of Power. Ключ не запускается.",
    OPT_SOUND = "Боевые звуки",
    OPT_SOUND_DESC = "Включить голосовые команды в бою.",
    OPT_PER_ACTION = "Звуки действий",
    OPT_SOUND_HINT = "Включите нужные действия или прослушайте их кнопкой справа.",
    OPT_PLAY_ALL = "Прослушать все",
    OPT_RESET_SOUNDS = "Сбросить звуки",
    OPT_PLAY_VICTORY = "Звук победы",
    NECROTIC_HEAL_FMT = "Лечение и поглощение -%d%%",
    NECROTIC_TICK_FMT = "последний тик %d",
    MAX_HEALTH_REDUCTION_FMT = "Макс. здоровье -%d%%",
    ARMOR_REDUCTION_FMT = "Броня -%d%%",
    DAMAGE_DONE_INCREASE_FMT = "Наносимый урон +%d%%",
    OILED_BLADE_FMT = "Получаемое лечение -75%",
    WITHERING_CURSE_FMT = "Получаемый урон +%d%%, наносимый -%d%%",
}

local STRINGS = BKA.locale == "ruRU" and RU or EN

function BKA:L(key, ...)
    local value = STRINGS[key] or EN[key] or key
    if select("#", ...) > 0 then
        local ok, formatted = pcall(string.format, value, ...)
        if ok then return formatted end
    end
    return value
end

local RU_ACTIONS = {
    ["CAST"] = "КАСТ",
    ["KICK"] = "КИК",
    ["STOP"] = "СТОП",
    ["CC"] = "КОНТРОЛЬ",
    ["TURN"] = "ОТВЕРНИ",
    ["AOE"] = "АОЕ",
    ["FRONTAL"] = "ФРОНТАЛ",
    ["CLEAVE"] = "КЛИВ",
    ["MOVE"] = "ВЫЙДИ",
    ["MOVE MOBS"] = "ВЫВЕДИ МОБОВ",
    ["DODGE"] = "УКЛОНИСЬ",
    ["GTFO"] = "ВЫЙДИ",
    ["TARGET"] = "ЦЕЛЬ",
    ["TARGETED"] = "ЦЕЛЬ",
    ["DISPEL"] = "ДИСПЕЛ",
    ["PURGE"] = "ПУРЖ",
    ["SOOTHE"] = "УСМИРИ",
    ["DEF"] = "СЕЙВ",
    ["DEFENSIVE"] = "СЕЙВ",
    ["HEAL"] = "ХИЛ",
    ["SOAK"] = "СОАК",
    ["SPREAD"] = "РАЗОЙДИСЬ",
    ["STACK"] = "СОБЕРИТЕСЬ",
    ["STACKS"] = "СТАКИ",
    ["RESET"] = "СБРОС",
    ["LOS"] = "ЛОС",
    ["RUN"] = "БЕГИ",
    ["FIXATE"] = "ФИКСАЦИЯ",
    ["KITE"] = "КАЙТ",
    ["PREWARN"] = "СКОРО",
    ["PREPARE"] = "ПРИГОТОВЬСЯ",
    ["ORB"] = "СФЕРА",
    ["INFO"] = "ИНФО",
    ["WATCH"] = "СЛЕДИ",
    ["INTERRUPT"] = "КИК",
    ["TANK"] = "ТАНК",
    ["YOU"] = "ТЫ",
    ["NONE"] = "",
    ["BURSTING"] = "ВЗРЫВНОЙ",
    ["STAGE"] = "ЭТАП",
    ["STAGE 2"] = "ЭТАП 2",
    ["ADD"] = "АДД",
    ["ADDS"] = "АДДЫ",
    ["WITHDRAW"] = "ОТХОД",
    ["RESUME"] = "ПРОДОЛЖАЙ",
    ["ORDNANCE"] = "БОЕПРИПАС",
    ["BURROW"] = "ЗАРЫВАНИЕ",
    ["INTERMISSION"] = "ПЕРЕХОДКА",
    ["SPEARS ACTIVE"] = "КОПЬЯ АКТИВНЫ",
    ["RUN / KITE"] = "БЕГИ / КАЙТ",
    ["CC / STOP"] = "КОНТРОЛЬ / СТОП",

    ["SOAK - TAINTED BLOOD"] = "СОАК - ЗАРАЖЕННАЯ КРОВЬ",
    ["PURGE - CLAWS"] = "ПУРЖ - КОГТИ",
    ["DISPEL - MOLTEN GOLD"] = "ДИСПЕЛ - РАСПЛАВЛЕННОЕ ЗОЛОТО",
    ["KILL - BARREL"] = "УБЕЙ - БОЧКА",
    ["SOAK - GOOD CRIT BREW"] = "СОАК - НАПИТОК КРИТА",
    ["SOAK - GOOD HASTE BREW"] = "СОАК - НАПИТОК СКОРОСТИ",
    ["MOVE - BAD BREW"] = "ВЫЙДИ - ПЛОХОЙ НАПИТОК",
    ["STACK - GOLD"] = "СОБЕРИТЕСЬ - ЗОЛОТО",
    ["CC - GOLD ADDS"] = "КОНТРОЛЬ - ЗОЛОТЫЕ АДДЫ",
    ["FIND - COFFIN"] = "НАЙДИ - ГРОБ",
    ["RUN - AGAINST WAVE"] = "БЕГИ - ПРОТИВ ВОЛНЫ",
    ["MOVE MOBS - OUT OF WARD"] = "ВЫВЕДИ МОБОВ - ИЗ ЗОНЫ",
    ["KITE - VOID ORBS"] = "КАЙТ - СФЕРЫ БЕЗДНЫ",
    ["BREAK - MINDBENDER"] = "СЛОМАЙ - МАЙНДБЕНДЕР",
    ["DISPEL - MIND REND"] = "ДИСПЕЛ - РАЗРЫВ РАЗУМА",
    ["MOVE BOSS - OUT OF GATE"] = "ВЫВЕДИ БОССА - ИЗ ВРАТ",
    ["DODGE - TENTACLE"] = "УКЛОНИСЬ - ЩУПАЛЬЦЕ",
    ["SWAP - SHIELDED BOSS"] = "СМЕНИ ЦЕЛЬ - БОСС ПОД ЩИТОМ",
    ["SPREAD - 8Y"] = "РАЗОЙДИСЬ - 8 М",
    ["PUNT - BOMBS"] = "ОТКИНЬ - БОМБЫ",
    ["CC - EARTHRAGER"] = "КОНТРОЛЬ - АДД",
    ["KILL - INFUSED ADD"] = "УБЕЙ - УСИЛЕННЫЙ АДД",
    ["DEFENSIVE - FIRE ROUNDS"] = "СЕЙВ - ОГНЕННЫЕ ПАТРОНЫ",
    ["MOVE - KNOCKBACK ROUNDS"] = "ВЫЙДИ - ОТБРАСЫВАЮЩИЕ ПАТРОНЫ",
    ["MOVE - BARRELS"] = "ВЫЙДИ - БОЧКИ",
    ["DISPEL - NO BARREL"] = "ДИСПЕЛ - БЕЗ БОЧКИ",
    ["SOAK - CLEANSE BLOOD"] = "СОАК - ОЧИСТИ КРОВЬ",
    ["CLEAR - SPORES"] = "ОЧИСТИ - СПОРЫ",
    ["DODGE - PODS"] = "УКЛОНИСЬ - КАПСУЛЫ",
    ["KILL - SOUL THORNS"] = "УБЕЙ - ШИПЫ ДУШИ",
    ["DEFENSIVE - STACK RESET"] = "СЕЙВ - СБРОС СТАКОВ",
    ["FOCUS - IRIS BOSS"] = "ФОКУС - БОСС С ИРИСОМ",
    ["DEFENSIVE - DIRE RITUAL"] = "СЕЙВ - РИТУАЛ",
    ["KILL - SERVANTS"] = "УБЕЙ - СЛУГИ",
    ["ADDS - KILL"] = "АДДЫ - УБЕЙ",
    ["ADD - KILL"] = "АДД - УБЕЙ",
    ["BURN - CORPSES"] = "СОЖГИ - ТРУПЫ",
    ["KITE - IRON GAZE"] = "КАЙТ - ЖЕЛЕЗНЫЙ ВЗГЛЯД",
    ["PICK - ORDNANCE"] = "ПОДБЕРИ - БОЕПРИПАС",
    ["DODGE - BREAK WATER"] = "УКЛОНИСЬ - ВОЛНА",
    ["LOS - STATUE"] = "ЛОС - СТАТУЯ",
}

function BKA:LocalizeAction(action)
    if action == nil then return "" end
    local key = string.upper(tostring(action))
    key = string.gsub(key, "_", " ")
    key = string.gsub(key, "%s+", " ")
    key = string.gsub(key, "^%s+", "")
    key = string.gsub(key, "%s+$", "")
    if self.locale == "ruRU" then
        if RU_ACTIONS[key] then return RU_ACTIONS[key] end
        local stage = string.match(key, "^STAGE%s+(%d+)$")
        if stage then return "ЭТАП " .. stage end
        return key
    end
    if key == "GTFO" then return "MOVE" end
    return key
end

function BKA:LocalizeToken(value)
    if value == "YOU" then return self:L("YOU") end
    if value == "TANK" then return self:L("TANK") end
    return self:LocalizeDetail(value)
end

function BKA:LocalizeFrontalState(value)
    if not value then return nil end
    if value == "FIXED" then return self:L("FIXED") end
    if value == "LOCKED" then return self:L("LOCKED") end
    if value == "TRACK" then return self:L("TRACK") end
    if value == "TRACKING" then return self:L("TRACKING") end
    return value
end

local RU_DETAILS = {
    ["Fixed frontal"] = "Фиксированный фронтал",
    ["Frontal on teammate"] = "Фронтал в союзника",
    ["Personal locked frontal"] = "Фронтал в тебя с фиксацией",
    ["Personal tracking frontal"] = "Фронтал следит за тобой",
    ["Frontal prediction"] = "Скоро фронтал",
    ["Active interrupt"] = "Активный кик",
    ["Council stage"] = "Этап совета",
    ["Stage 2"] = "Этап 2",
    ["Viq'Goth stage"] = "Этап Вик'Гота",
    ["Intermission"] = "Переходка",
    ["Intermission over"] = "Переходка закончилась",
    ["Heart Guardian"] = "Страж сердца",
    ["Plague Doctor"] = "Чумной доктор",
    ["Demolishing Terror"] = "Разрушительный ужас",
    ["Hoodoo Hexer"] = "Колдун худу",
    ["Reban soon"] = "Скоро Reban",
    ["T'zala soon"] = "Скоро T'zala",
    ["SPEARS SOON"] = "СКОРО КОПЬЯ",
    ["OVER"] = "ЗАКОНЧИЛОСЬ",
    ["SPAWNED"] = "ПОЯВИЛСЯ",
}

function BKA:LocalizeDetail(value)
    if value == nil then return "" end
    local text = tostring(value)
    if self.locale ~= "ruRU" then return text end
    if RU_DETAILS[text] then return RU_DETAILS[text] end
    local count = string.match(text, "^(%d+)%s+remaining$")
    if count then return count .. " " .. self:L("REMAINING") end
    local stage = string.match(text, "^Stage%s+(%d+)$")
    if stage then return "Этап " .. stage end
    local demolisher = string.match(text, "^Demolishing Terror%s+(%d+)$")
    if demolisher then return "Разрушительный ужас " .. demolisher end
    return text
end

local SPELL_ALIASES = {
    CURSED_PULSE = {
        ["Cursed Pulse"] = true,
        ["Проклятый импульс"] = true,
        ["Проклятый пульс"] = true,
    },
}

function BKA:IsSpellAlias(aliasKey, spellName)
    if not spellName then return false end
    local aliases = SPELL_ALIASES[aliasKey]
    return aliases and aliases[spellName] == true or false
end
